[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 921600

; Dependencies for the CYD Screen and Touch
lib_deps =
  bodmer/TFT_eSPI @ ^2.5.31
  https://github.com/PaulStoffregen/XPT2046_Touchscreen.git

; Configure TFT_eSPI directly via build flags
build_flags =
  -D USER_SETUP_LOADED=1
  -D ST7789_DRIVER=1
  -D TFT_MISO=12
  -D TFT_MOSI=13
  -D TFT_SCLK=14
  -D TFT_CS=15
  -D TFT_DC=2
  -D TFT_RST=-1
  -D TFT_BL=27
  -D TFT_BACKLIGHT_ON=HIGH
  -D LOAD_GLCD=1
  -D LOAD_FONT2=1
  -D LOAD_FONT4=1
  -D SPI_FREQUENCY=55000000
  -D SPI_READ_FREQUENCY=20000000
  -D SPI_TOUCH_FREQUENCY=2500000